name: FlagsBorderPatrol
version: 1.0.0-B1
description: Module that adds border crossing flags to the Flags plugin.
author: Alshain01
website: http://dev.bukkit.org/bukkit-plugins/flags/
main: alshain01.FlagsBorderPatrol.FlagsBorderPatrol
depend: [Flags]